title: Electron avalanche
email: niels.pichon@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Cascading ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nielspichon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  NielsPichon

# Build settings
remote_theme: broccolini/swiss
plugins:
  - jekyll-feed
  - jekyll-remote-theme


highlighter: rouge
